urls:
  redhatUrl: ../testPages/redhatTestPage.html
  githubUrl: ../testPages/githubTestPage.mhtml

comments:
  comment: "comment"

githubAuth:
  owner: User123
  repo: my_repo
  token: xxxxxxxxxx
  path: path/to/file.mk
  branch: branch1

gihtubReviewers:
  reviewers: reviewer1,reviewer2,reviewer3