urls:
  redhatUrl: https://catalog.redhat.com/software/containers/ubi9/ubi-micro/615bdf943f6014fa45ae1b58?architecture=amd64
  githubUrl: https://github.com/WilsonRadadia20/my_CSM/blob/main/csm-main/config/csm-common.mk

comments:
  comment: "# Common base image for all CSM images. When base image is upgraded, do not update anything as it is automated."

githubAuth:
  owner: WilsonRadadia20
  repo: my_CSM
  token: xxxxxxxxxxxxxx
  path: csm-main/config/csm-common.mk
  branch: User_branch_1

gihtubReviewers:
  reviewers: AkshaySainiDell,suryagupta4,rishabhatdell